server:
  enable: true
  backend: local
  project_name: rl-insight-monitor

prometheus:
  enable: true
  min_version: 2.30.0
  install_version: 2.54.1
  prometheus_port: 9090
  retention_time: 30d
  config_file: prometheus.yml

otel:
  traces_endpoint: http://127.0.0.1:4318/v1/traces

tempo:
  enable: true
  min_version: 2.0.0
  install_version: 2.6.1
  query_port: 3200
  retention_time: 30d
  config_file: tempo.yaml

grafana:
  enable: true
  min_version: 9.0.0
  install_version: 11.6.3
  port: 3000
  config_file: grafana.ini
  provisioning_dir: provisioning
  dashboards_dir: dashboards
